name: List Repository Branches

on:
  workflow_dispatch:

jobs:
  list-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List branches with GitHub API
        env:
          GITHUB_TOKEN: ${{ secrets.Deepa }}  # Ensure this secret is available in repository settings
        run: |
          curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/deepar-deepu/dev_repdev_rep/branches | jq '.[].name'
